content:
  - name: project
    label: Projects
    path: src/content/open-source.yaml
    type: file
    list: true
    fields:
      - name: name
        label: Name
        type: string
      - name: url
        label: URL
        type: string
      - name: image
        label: Image
        type: image
      - name: description
        label: Description
        type: rich-text