content:
  - name: project
    label: Projects
    path: src/content/open-source.yaml
    type: object
    fields:
      - name: name
        label: Name
        type: string
      - name: url
        label: URL
        type: string
      - name: description
        label: Description
        type: rich-text