content:
  - name: project
    label: Projects
    path: src/content/open-source.yaml
    type: collection
    fields:
      - name: name
        label: Name
        type: text
      - name: url
        label: URL
        type: string
      - name: description
        label: Description
        type: rich-text