content:
  - name: project
    label: Projects
    path: src/content
    filename: "{id}.yaml"
    type: collection
    format: yaml
    fields:
      - name: name
        label: Name
        type: string
      - name: url
        label: URL
        type: string
      - name: description
        label: Description
        type: rich-text