source 'http://rubygems.org'

gem 'sinatra'
gem 'coffee-script'
gem 'uglifier'
gem 'therubyracer'
gem 'rack', '~> 1.3.5'
gem 'rack-cache'
gem 'rack-thumb', require: 'rack/thumb'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'erubis'
gem 'sprockets'
gem 'kramdown'
gem 'babosa'
gem 'coderay'
gem 'i18n'
gem 'activesupport'
gem 'unicorn'