source 'http://rubygems.org'

gem 'sinatra'
gem 'coffee-script'
gem 'uglifier'
gem 'rack-cache'
gem 'rack-thumb'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'sprockets'
gem 'kramdown'
gem 'babosa'
gem 'coderay'
gem 'i18n'
gem 'activesupport'