on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Get bun cache directory path
        id: bun-cache-dir-path
        run: echo "dir=$(bun pm cache path)" >> "$GITHUB_OUTPUT"

      - name: Cache bun dependencies
        uses: actions/cache@v4
        id: bun-cache
        with:
          path: ${{ steps.bun-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --no-tags --prune --depth=1 origin gh-pages
          git worktree add dist gh-pages

      - name: Build
        run: |
          rm -rf dist/**/*
          bun run build
          cd dist
          git add -f .
          git commit -m "$(date +%Y%m%d)" || true
          git push || true
